version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
        environment:
          FIREFOX_BIN: "/usr/bin/firefox"
    steps:
      - checkout
      - restore_cache:
          key: dependency-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run test
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
           name: Initiate XL Release
           command: |
            pip install httpie && http --auth admin:admin POST http://circleci.seaconxlr.ultrahook.com?template="testTemplate" buildNumber=${CIRCLE_BUILD_NUM} 
#      - run:
#          name: Build and Push Image to Docker Hub
#          command: |
#            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
#            echo 'export IMAGE_NAME=crime-data-frontend' >> $BASH_ENV
#            source $BASH_ENV
#            docker build -t $DOCKER_LOGIN/$IMAGE_NAME -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
#            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
#            docker push $DOCKER_LOGIN/$IMAGE_NAME
